/* eslint-disable */
// @ts-nocheck
// This file is auto-generated by payload generate:types
// Do not manually modify this file

export interface Config {
    collections: {
        users: User;
        services: Service;
        transactions: Transaction;
        'travel-docs': TravelDoc;
        tasks: Task;
        cashflow: Cashflow;
        media: Media;
    };
}

export interface User {
    id: string;
    name: string;
    role: 'direktur' | 'bendahara' | 'sekretaris' | 'bpupd' | 'bppg' | 'staff';
    pin?: string;
    phoneWA?: string;
    deviceId?: string;
    otpSecret?: string;
    avatar?: string | Media;
    email: string;
    createdAt: string;
    updatedAt: string;
}

export interface Service {
    id: string;
    category: 'hotel' | 'homestay' | 'aula' | 'travel' | 'rental';
    name: string;
    description?: string;
    priceUSD: number;
    priceEGP: number;
    unit?: 'night' | 'day' | 'hour' | 'package' | 'item';
    isActive?: boolean;
    image?: string | Media;
    createdAt: string;
    updatedAt: string;
}

export interface Transaction {
    id: string;
    invoiceNo: string;
    customerName: string;
    customerWA: string;
    customerEmail?: string;
    items?: {
        service: string | Service;
        quantity: number;
        startDate?: string;
        endDate?: string;
        priceUnit?: number;
        subtotal?: number;
        id?: string;
    }[];
    currency?: 'USD' | 'EGP';
    totalAmount: number;
    paymentStatus?: 'pending' | 'partial' | 'paid' | 'cancelled';
    paymentMethod?: 'cash' | 'transfer' | 'instapay';
    officer?: string | User;
    invoicePdf?: string | Media;
    waSent?: boolean;
    notes?: string;
    createdAt: string;
    updatedAt: string;
}

export interface TravelDoc {
    id: string;
    transaction?: string | Transaction;
    passengerName: string;
    passportNo: string;
    passportExpiry?: string;
    nationality?: string;
    travelType?: 'umrah' | 'haji' | 'tour' | 'ticket';
    visaStatus?: 'pending_docs' | 'on_process' | 'issued' | 'rejected';
    documents?: {
        docType?: 'passport' | 'photo' | 'visa' | 'ticket' | 'other';
        file?: string | Media;
        id?: string;
    }[];
    notes?: string;
    createdAt: string;
    updatedAt: string;
}

export interface Task {
    id: string;
    title: string;
    description?: string;
    category?: 'housekeeping' | 'maintenance' | 'inventory' | 'admin';
    priority?: 'high' | 'normal' | 'low';
    status?: 'pending' | 'in_progress' | 'done';
    relatedRoom?: string;
    assignee?: string | User;
    dueDate?: string;
    completedAt?: string;
    photos?: {
        image?: string | Media;
        caption?: string;
        id?: string;
    }[];
    createdAt: string;
    updatedAt: string;
}

export interface Cashflow {
    id: string;
    type: 'in' | 'out';
    amount: number;
    currency?: 'EGP' | 'USD';
    category?: 'piket' | 'petty' | 'salary' | 'operational' | 'maintenance' | 'other';
    description: string;
    transaction?: string | Transaction;
    proofImage?: string | Media;
    approvalStatus?: 'pending' | 'approved' | 'rejected';
    approvedBy?: string | User;
    approvedAt?: string;
    notes?: string;
    createdAt: string;
    updatedAt: string;
}

export interface Media {
    id: string;
    alt?: string;
    url?: string;
    filename?: string;
    mimeType?: string;
    filesize?: number;
    width?: number;
    height?: number;
    createdAt: string;
    updatedAt: string;
}
